# Anotações do dia 30-01-2021

- Implementando uma fila (queue) em clojure, para isso é necessário utilizar ``` clojure.lang.PersistentQueue/EMPTY``` portanto vamos ao exemplo: 

```

(def nova-fila clojure.lang.PersistentQueue/EMPTY)

(defn fila-vacinacao []
  (println "Fila Vacinação")
  (pprint (conj nova-fila 90 85 80 75)))

(fila-vacinacao)

```
**Output:**

```
#object[clojure.lang.PersistentQueue 0x4351171a clojure.lang.PersistentQueue@1]

```

Um pouco ruim de entender o que está acontecendo né? Para melhorar você pode utilizar a função ```pprint``` basicamente o que ela faz é formatar a informação que você está enviando de forma mais legivel, mas para isso é necessário importar no namespace que você está utilizando para isso utilizaremos o```use```: 

```
(ns exemplo.core
  (:use [clojure.pprint]))

(defn fila-vacinacao []
  (let [fila clojure.lang.PersistentQueue/EMPTY]
    (println "Fila Vacinação")
    (pprint (conj fila 90 85 80 75))))

(fila-vacinacao)
```

**Output:**
```
Fila Vacinação
<-(90 85 80 75)-<
```

- Função **"throw"** pode ser utilizada quando você desejar retornar uma exceção para o usuário, para demonstrar vamos definir uma regra para o tamanho do nosso vetor e caso o limite seja ultrapassado vamos retornar uma exceção para o usuário:

Para facilitar o teste vamos criar dois vetores que checamos o seu tamanho:

```
(def vetorCheio [1 2 3 4 5 6])
(def vetorComVaga [1 2 3 4])

```
E apos vamos definir a função que checa o tamanho do vetor, temos uma condição que checa se o tamanho do vetor é maior que 5 elementos e caso seja retorna exceção utilizando a função **"throw"**, utilizando a função ```ex-info``` que é responsavel por adicionar algumas informações a mais a exceção, no nosso caso "Vetor ja está cheio":
```
(defn tem-vaga-no-vetor? [fila]
  (if (>= (count fila) 5)
    (throw (ex-info "Vetor ja está cheio" {:tentando-add vetor}))
    true))
```
Quando executamos a função os outputs são os seguintes: 

**Cenario de erro:**
```
(tem-vaga-na-vetor? vetorCheio)
```
**Output:**

```
Execution error (ExceptionInfo) at loja.core/tem-vaga-na-fila? (form-init3220695797824362203.clj:3).
Vetor ja está cheia ;Mensagem que definimos
```
**Cenario de sucesso:**
```
(tem-vaga-na-vetor? vetorComVaga)
```
**Output:** 
```
=> true
```